#!/usr/bin/env python3
"""Generate the repo-root STATUS.md dashboard from machine-readable sources.

Generated status stays current because `--check` regenerates it and fails CI
on drift.

Sources — nothing else feeds the dashboard, and it is never hand-edited:
  - v0.5/CHANGELOG.md                    current release + recent entries
  - .playbook-maintenance.yml            upstream-drift cadence state
  - bench/results/*/SUMMARY.md           newest committed benchmark evidence
  - analysis/STATUS.md                   active analysis/planning documents

Deterministic by construction: no clock reads — every date in the output is
derived from a source file, so regenerating without source changes is a no-op.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from playbook_state import parse_top_level_map, top_level_scalar_value  # noqa: E402
import upstream_registry  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "STATUS.md"
ENTRY_RE = re.compile(r"^##\s+(V\d+\.\d+\.\d+)\s+—\s+(\d{4}-\d{2}-\d{2})\s*$", re.M)


def changelog_entries(text: str, limit: int = 3) -> list[dict]:
    entries = []
    matches = list(ENTRY_RE.finditer(text))
    for index, match in enumerate(matches[:limit]):
        end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        body = text[match.end():end].strip()
        first_line = body.splitlines()[0].strip() if body else ""
        entries.append({"version": match.group(1), "date": match.group(2),
                        "summary": first_line})
    return entries


def newest_bench_run(root: Path) -> dict | None:
    probe = subprocess.run(
        ["git", "-C", str(root), "rev-parse", "--is-inside-work-tree"],
        text=True,
        capture_output=True,
        check=False,
    )
    if probe.returncode == 0:
        tracked = subprocess.run(
            ["git", "-C", str(root), "ls-tree", "-r", "--name-only", "HEAD", "--",
             "bench/results"],
            text=True,
            capture_output=True,
            check=False,
        )
        names = tracked.stdout.splitlines() if tracked.returncode == 0 else []
        summaries = sorted(root / name for name in names if name.endswith("/SUMMARY.md"))
    else:
        # --root fixtures need not be Git repositories; all supplied summaries
        # are their explicit source set.
        summaries = sorted((root / "bench" / "results").glob("*/SUMMARY.md"))
    if not summaries:
        return None
    newest = summaries[-1]
    text = newest.read_text()
    completed = re.search(r"(\d+) completed run\(s\)", text)
    models = re.findall(r"^## Model: (.+)$", text, re.M)
    runner = re.search(r"\bRunners?:\s*([^·\n]+)", text)
    pass_counts = re.findall(
        r"^\|\s*[^|]+\|\s*[^|]+\|\s*\d+\s*\|\s*(\d+)\s*/\s*(\d+)\s*\|",
        text,
        re.M,
    )
    passed = sum(int(value) for value, _ in pass_counts)
    evaluated = sum(int(value) for _, value in pass_counts)
    return {
        "run_id": newest.parent.name,
        "date": newest.parent.name[:10],
        "completed": int(completed.group(1)) if completed else None,
        "models": models,
        "runner": runner.group(1).strip() if runner else "not recorded",
        "passed": passed,
        "evaluated": evaluated,
    }


def analysis_active_lines(root: Path) -> list[str]:
    status = root / "analysis" / "STATUS.md"
    if not status.is_file():
        return []
    lines: list[str] = []
    in_active = False
    for line in status.read_text().splitlines():
        if line.startswith("## "):
            in_active = line.lower().startswith("## active")
            continue
        if in_active and line.startswith("- "):
            # Links in analysis/STATUS.md are relative to analysis/. The generated
            # dashboard lives one level higher, so preserve their destinations.
            lines.append(re.sub(r"\]\((?!https?://|analysis/)([^)]+)\)",
                                r"](analysis/\1)", line))
    return lines


def render(root: Path) -> str:
    entries = changelog_entries((root / "v0.5" / "CHANGELOG.md").read_text())
    maintenance_text = (root / ".playbook-maintenance.yml").read_text()
    upstreams = parse_top_level_map(maintenance_text, "upstreams")
    registry = upstream_registry.load(root / "v0.5" / "upstream-skills.json")
    bench = newest_bench_run(root)
    active = analysis_active_lines(root)

    current = entries[0] if entries else {"version": "unknown", "date": "unknown", "summary": ""}
    previous = entries[1] if len(entries) > 1 else None

    lines = [
        "# Playbook status",
        "",
        "> Generated by `v0.5/scripts/generate-status.py` — **do not hand-edit**.",
        "> Regenerate after changing any source: `python3 v0.5/scripts/generate-status.py`.",
        "> CI fails when this file drifts from its sources (`--check`).",
        "",
        "## Release",
        "",
        f"**{current['version']}** — {current['date']}. {current['summary']}",
        "",
    ]
    for entry in entries[1:]:
        lines.append(f"- {entry['version']} — {entry['date']}. {entry['summary']}")
    if len(entries) > 1:
        lines.append("")
    lines += [
        "Full history: [`v0.5/CHANGELOG.md`](v0.5/CHANGELOG.md).",
        "",
        "## Gates",
        "",
        "Canonical release-readiness suite: `python3 v0.5/scripts/verify-playbook.py`",
        "Gate health is evaluated when this command runs; the dashboard does not persist",
        "environment-dependent exit codes. The latest authoritative result is local or CI output.",
        "(unit tests + interactive-doc, md-convention, skill-metadata, link-integrity,",
        "status-dashboard, public-content, manifest, K4.1 delivery, and upstream-drift",
        "checks). PR CI",
        "splits privileged delivery verification into its own job; the main job skips that",
        "split suite and drift, while the weekly maintenance cron keeps the strict set.",
        "",
        "## Benchmark evidence",
        "",
    ]
    if bench is None:
        lines.append("- No committed benchmark summaries in `bench/results/`.")
    else:
        models = ", ".join(bench["models"]) or "unknown"
        completed = bench["completed"] if bench["completed"] is not None else "?"
        lines.append(f"- Newest committed run: `{bench['run_id']}` — "
                     f"{completed} completed run(s). Runner: {bench['runner']}; "
                     f"models: {models}.")
        if bench["evaluated"]:
            rate = bench["passed"] / bench["evaluated"] * 100
            lines.append(f"- Result: {bench['passed']}/{bench['evaluated']} passed "
                         f"({rate:.1f}%) across summary rows.")
        if previous is not None:
            if bench["date"] >= previous["date"]:
                lines.append(f"- Current for this release cycle "
                             f"(newer than {previous['version']}, {previous['date']}).")
            else:
                lines.append(f"- **Stale**: predates the previous release "
                             f"({previous['version']}, {previous['date']}) — run the "
                             f"per-release loop in [`bench/README.md`](bench/README.md).")
    lines += [
        "",
        "## Upstream maintenance",
        "",
        f"- Last verified {top_level_scalar_value(maintenance_text, 'last_verified')}; "
        f"next due {top_level_scalar_value(maintenance_text, 'next_due')} "
        f"({top_level_scalar_value(maintenance_text, 'cadence')} cadence, "
        f"procedure: [`v0.5/MAINTENANCE.md`](v0.5/MAINTENANCE.md)).",
        "- Upstream versions: "
        + "; ".join(f"{name} {value}" for name, value in upstreams.items()) + ".",
        "",
        "## Upstream packages",
        "",
        "| Package | Level | Pin | Verified | Skills named |",
        "|---|---|---|---|---:|",
    ]
    for name, package in registry.packages.items():
        if package.pin.get("kind") == "commit+version":
            pin = f"{package.pin['value']} ({package.pin['commit'][:7]})"
        else:
            pin = package.pin.get("value") or package.pin.get("commit") or "—"
        verified = package.pin.get("verified", "—")
        level = package.adoption_level or "local"
        skills = len(registry.skills_for(name))
        lines.append(f"| {name} | {level} | {pin} | {verified} | {skills} |")
    lines += [
        "",
        "## Active analysis documents",
        "",
    ]
    if active:
        lines += active
        lines.append("")
        lines.append("Index: [`analysis/STATUS.md`](analysis/STATUS.md). "
                     "Archived docs live in `analysis/archive/` (agents do not read it).")
    else:
        lines.append("*(none tracked — see [`analysis/STATUS.md`](analysis/STATUS.md))*")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail (exit 1) if STATUS.md differs from its sources")
    parser.add_argument("--root", type=Path, default=ROOT, help="repo root (tests)")
    args = parser.parse_args(argv)

    rendered = render(args.root)
    output = args.root / "STATUS.md"
    if args.check:
        existing = output.read_text() if output.is_file() else None
        if existing != rendered:
            print("STATUS.md is stale or hand-edited — regenerate with "
                  "`python3 v0.5/scripts/generate-status.py`.")
            return 1
        print("STATUS.md matches its sources.")
        return 0
    output.write_text(rendered)
    print(f"Wrote {output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
